In [343]:
import numpy as np

# http://mechatorodiy.blog.fc2.com/blog-entry-7.html

In [447]:
p = 0 # This is pich value x -1 other value is direct 
y = -20/180*3.14
w = 0 #west

In [448]:
p1 = np.array([[0,0,14.5]])

r1 = np.array([[np.cos(w),-np.sin(w),0],
              [np.sin(w),np.cos(w),0],
              [0,0,1]])

p2 = np.array([[8,0,33.5]])

r2 = np.array([[np.cos(y),-np.sin(y),0],
              [np.sin(y),np.cos(y),0],
              [0,0,1]])

p3 = np.array([[0,0,4]])


r3 = np.array([[np.cos(p),0,np.sin(p)],
              [0,1,0],
              [-np.sin(p),0,np.cos(p)]])

p4 = np.array([[7,3.5,10]])

e = np.array([[1,0,0],[0,1,0],[0,0,1]])
zeros = np.array([[0,0,0]])

In [449]:
v1 = np.concatenate((e,p1.T),axis=1)
v2 = np.concatenate((r1,zeros.T),axis=1)
v3 = np.concatenate((e,p2.T),axis=1)
v4 = np.concatenate((r2,zeros.T),axis=1)
v5 = np.concatenate((e,p3.T),axis=1)
v6 = np.concatenate((r3,zeros.T),axis=1)
v7 = np.concatenate((e,p4.T),axis=1)

# v1 = np.concatenate((e,p1.T),axis=1)
# v2 = np.concatenate((r1,p2.T),axis=1)
# v3 = np.concatenate((r2,p3.T),axis=1)
# v4 = np.concatenate((r3,p4.T),axis=1)


# v1 = np.concatenate((r1.T,np.dot(-r1.T,p1.T)),axis=1)
# v2 = np.concatenate((r2.T,np.dot(-r2.T,p2.T)),axis=1)
# v3 = np.concatenate((r3.T,np.dot(-r3.T,p3.T)),axis=1)
# v4 = np.concatenate((e.T,np.dot(-e.T,p4.T)),axis=1)

In [450]:
x = np.array([0,0,0,1])

In [451]:
z = x
for v in [v7, v6, v5, v4, v3, v2, v1]:
    v = np.concatenate((v,np.array([[0,0,0,1]])))
    z = np.dot(v,z)

In [452]:
z

array([15.77476038,  0.89615902, 62.        ,  1.        ])

In [423]:
v6 = np.concatenate((v6,np.array([[0,0,0,1]])))
v6

array([[ 0.93975313,  0.        , -0.34185385,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.34185385,  0.        ,  0.93975313,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [424]:
v7 = np.concatenate((v7,np.array([[0,0,0,1]])))
v7

array([[ 1. ,  0. ,  0. ,  7. ],
       [ 0. ,  1. ,  0. ,  3.5],
       [ 0. ,  0. ,  1. , 10. ],
       [ 0. ,  0. ,  0. ,  1. ]])

In [425]:
np.dot(v7,x)

array([ 7. ,  3.5, 10. ,  1. ])

In [426]:
np.dot(v6,np.dot(v7,x))

array([ 3.15973343,  3.5       , 11.79050824,  1.        ])

In [427]:
x = np.array([1,0,0,1])
np.dot(v6, x)

array([0.93975313, 0.        , 0.34185385, 1.        ])

In [446]:
r3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [-0.,  0.,  1.]])